[package]
name = "bart"
version = "0.1.0"
edition = "2021"
description = "BART API client library"

[lib]
name = "bart"
path = "src/lib.rs"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
